name: Build & Deploy to production

on:
  push:
    branches: [ "develop" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/linkstart-bot-image:latest

      - name: Deploy to Production
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker stop linkstart-bot
            docker container rm linkstart-bot
            docker image rm ${{ secrets.DOCKER_USERNAME }}/linkstart-bot-image
            docker pull ${{ secrets.DOCKER_USERNAME }}/linkstart-bot-image
            docker run -d \
            -e DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }} \
            -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} \
            -e API_URL=${{ secrets.API_URL }} \
            -e CLIENT_NAME=${{ secrets.CLIENT_NAME }} \
            -e CLIENT_PASSWORD=${{ secrets.CLIENT_PASSWORD }} \
            --net="linkstart" \
            --restart=unless-stopped \
            -v ~/linkstart-bot-musics:/app/music-files \
            --name linkstart-bot \
            ${{ secrets.DOCKER_USERNAME }}/linkstart-bot-image:latest
