name: Build & Deploy to production

on:
  push:
    branches: [ "develop" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }}" > .env
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
          echo "API_URL=${{ secrets.API_URL }}" >> .env
          echo "CLIENT_NAME=${{ secrets.CLIENT_NAME }}" >> .env
          echo "CLIENT_PASSWORD=${{ secrets.CLIENT_PASSWORD }}" >> .env

      - name: Build Docker Image
        run: |
          docker build -t linkstart-bot-image .
          docker tag linkstart-bot-image ${{ secrets.DOCKER_USERNAME }}/linkstart-bot-image:latest

      - name: Push Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin 
          docker push ${{ secrets.DOCKER_USERNAME }}/linkstart-bot-image:latest

      - name: Deploy to Production
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker stop linkstart-bot
            docker container rm linkstart-bot
            docker image rm ${{ secrets.DOCKER_USERNAME }}/linkstart-bot-image
            docker pull ${{ secrets.DOCKER_USERNAME }}/linkstart-bot-image
            docker run -d \
            --net="linkstart" \
            --restart=unless-stopped \
            -v ~/linkstart-bot-musics:/app/music-files \
            --env-file .env \
            --name linkstart-bot \
            ${{ secrets.DOCKER_USERNAME }}/linkstart-bot-image:latest
