name: Build & Deploy to production

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Create .env file
      run: |
        echo "DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }}" > .env
        echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
        echo "API_URL=${{ secrets.API_URL }}" >> .env
        echo "CLIENT_NAME=${{ secrets.CLIENT_NAME }}" >> .env
        echo "CLIENT_PASSWORD=${{ secrets.CLIENT_PASSWORD }}" >> .env
        echo "RCON_HOST=${{ secrets.RCON_HOST }}" >> .env
        echo "RCON_PORT=${{ secrets.RCON_PORT }}" >> .env
        echo "RCON_PASSWORD=${{ secrets.RCON_PASSWORD }}" >> .env
        echo "DEEZER_DECRYPTION_KEY=${{ secrets.DEEZER_DECRYPTION_KEY }}" >> .env

    - name: Delete old Docker image & container
      run: |
        docker stop linkstart-bot
        docker container rm linkstart-bot
        docker image rm linkstart-bot-image

    - name: Build Docker Image
      run: |
        docker build -t linkstart-bot-image .

    - name: Run container
      run: |
          docker run -d --net="linkstart" --restart=unless-stopped -v /home/martin/dev/lk-musics:/app/music-files --name linkstart-bot linkstart-bot-image
