name: Deploy Docker Container

on:
  push:
    branches: [ "master" ]

env:
  HOST: Monday

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create .env file
      run: |
        echo "DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }}" > .env
        echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
        echo "API_URL=${{ secrets.API_URL }}" >> .env
    - name: Build Docker Image
      run: |
        docker build -t linkstart-bot-image .
        docker tag linkstart-bot-image garwalle/linkstart-bot-image:latest
    - name: Push Docker Image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin 
        docker push garwalle/linkstart-bot-image:latest
    - name: Deploy to Production
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          touch /root/test.txt
          docker stop linkstart-bot
          docker container rm linkstart-bot
          docker image rm garwalle/linkstart-bot-image
          docker pull garwalle/linkstart-bot-image
          docker run -d --net="linkstart" --name linkstart-bot garwalle/linkstart-bot-image
